services:
  - type: web
    name: projeto-back
    env: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    branch: dev
    envVars:
      - key: JAVA_VERSION
        value: 24
