services:
  - type: web
    name: InfoWeg-Backend
    env: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    branch: dev
    envVars:
      - key: JAVA_VERSION
        value: 21
