spring.application.name=InfoWeg

spring.datasource.url=jdbc:postgresql:// dpg-d25agbbuibrs73dt8p40-a.ohio-postgres.render.com:5432/sistema_de_informativos
spring.datasource.username=sistema_de_informativos_user
spring.datasource.password=IJPJap5Kq7JkCGZTDnlcj1E8ApKMAZ7B

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
