spring.application.name=InfoWeg

spring.datasource.url=jdbc:postgresql://dpg-d2aesvvgi27c73f88cs0-a.oregon-postgres.render.com:5432/sistema_infoweg
spring.datasource.username=user_infoweg
spring.datasource.password=bmmnn7raJCKsupbiGxIXj4Av4S8A5QMt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect